### ISSUE TITLE
what is the EphemeralKey?

### ISSUE THREAD

**Issue by Kelbie** [KZen-networks/multisig-schnorr#38]
I'm still learning about MuSig so sorry if this is obvious but I'm wondering what the Ephemeral Key is and if its part of the MuSig spec or an implementation detail. Also, what is the difference in using `EphemeralKey::create_from_private_key` over `EphemeralKey::create`, is there any reason to use one over the other?

**Comment by omershlo** [comment]
Hi!
Ephemeral key is what we call `r_i`  used in signing round 1 (see https://eprint.iacr.org/2018/483.pdf for Musig). We call it ephemeral because you must choose a fresh random key each time you sign (as opposed to the static key you generated during key generation). 

The `create` option does just that  - choose random `r_i`, compute `R =r_i G` and commit to it. 
The `create_from_private_key` is another way to make sure each signature uses different nonce (`r_i`) but without using a random number generator (some use case don't assume such exist that is secure).  in this method you compute something like `r_i  = H(m || static_key)`

**Comment by Kelbie** [comment]
Thanks for the speedy reply! That makes more sense, I also just watch a [video]( https://www.youtube.com/watch?v=j9Wvz7zI_Ac) by Poelstra which complements your explanation here. Closing this now.
